HW1
slavon0089/ViacheslavShchukin pull request #3
Opened 2022-12-09 11:28 UTC by slavon0089

2022-12-11 19:33 UTC, obitkin requested changes
- Rename repo to NameSurname
- Add me as collaborator in this repo

2022-12-11 19:33 UTC, obitkin commented on pom.xml
> +                </configuration>
Java version duplication. Remove

2022-12-11 19:33 UTC, obitkin commented on src/main/java/Main.java
>  }
You can just delete it

2022-12-11 19:33 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/AbstractTest.java
> +    }
Do you really need softAssert in all your classes? i think that SoftAssert should be method variable.

2022-12-11 19:33 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +        var act = calculator.div(a, b);
Remove unused `result` and `act`

2022-12-11 19:33 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
1. double(0.0 / doube(0.0) = double(Infinity) != 9223.0
2. softAssert is useless without `assertAll()` method. 
3. Why are you using softAssert here? Why not hard assert?

2022-12-11 19:33 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
Remove duplicated after method. Already used in AbstractTest

2022-12-12 18:37 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
Sorry, double(0.0 / doube(0.0) = double(NAN) != 9223.0
double(1.0 / doube(0.0) = double(Infinity) != 9223.0

2022-12-14 12:20 UTC, obitkin requested changes
Remove `.idea` files from PR

2022-12-14 12:20 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
Why is it here?

2022-12-14 13:13 UTC, obitkin requested changes

2022-12-14 13:13 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
_9.	Use AssertJ instead of basic TestNg asserts_

2022-12-14 13:14 UTC, slavon0089 commented on src/test/java/com/epam/tc/hw1/DivTest.java
> +    }
Duplicated by mistake from the parent class. Will be deleted.

2022-12-15 12:20 UTC, obitkin approved these changes
Approved

2022-12-15 15:37 UTC, merged